import type { ComboLandingContent } from '@/types/combo'

/**
 * Seed content for /combo (EPIC-006). The only thing a real CMS
 * integration needs to replace — see `lib/combo/combo-repository.ts`.
 *
 * === DEMO ASSET vs PRODUCTION ASSET ===
 * Every `src` below is one of two categories (see
 * docs/Handover/Combo/COMBO-MEDIA-REQUIREMENTS.md for the full table):
 *
 * - PRODUCTION (real Minh Việt-owned): `/images/hero/*` and
 *   `/videos/hero/ha-long-bay.mp4` — reused from the site's existing
 *   real destination photography (Hạ Long, Sa Pa, Ninh Bình).
 * - DEMO (licensed stock, for this demo only): everything under
 *   `/images/combo/*` and `/videos/hero/combo-hero-preview.mp4` —
 *   Pexels/Mixkit, free-for-commercial-use licenses, no attribution
 *   required. Chosen to be geographically honest (a "Phú Quốc" image is
 *   a real photo of Phú Quốc, not a generic beach) and free of the
 *   banned "person facing camera" cliché.
 *
 * Swapping any image later is a one-line edit here — every section
 * component reads only from `ComboLandingContent`, never a hardcoded path.
 */
export const comboLandingContentSeed: ComboLandingContent = {
  seo: {
    title: 'Combo du lịch trọn gói | Minh Việt Travel',
    description:
      'Khám phá các Combo du lịch trọn gói được Minh Việt chuẩn bị sẵn — vé máy bay, khách sạn và lịch trình trong một mức giá, hoặc để chúng tôi thiết kế riêng cho bạn.',
    canonicalPath: '/combo',
    ogImage: '/images/hero/ha-long-bay.jpg',
  },
  hero: {
    eyebrow: 'Combo du lịch',
    headline: 'Combo du lịch trọn gói',
    subheadline: 'Một kỳ nghỉ trọn vẹn. Minh Việt chuẩn bị mọi thứ cho bạn.',
    heroImage: {
      src: '/images/hero/combo-hero-preview.jpg',
      alt: 'Toàn cảnh bờ biển nhiệt đới nhìn từ trên cao lúc hoàng hôn',
      width: 1280,
      height: 720,
    },
    // DEMO asset — Mixkit Stock Video Free License (free for commercial use,
    // no attribution required): "Flying over a beautiful tropical landscape"
    // https://mixkit.co/free-stock-video/flying-over-a-beautiful-tropical-landscape-5369/
    // Re-encoded locally (H.264, CRF 30, audio stripped) from ~4.3MB to ~1.6MB.
    heroVideo: '/videos/hero/combo-hero-preview.mp4',
    primaryCta: { label: 'Khám phá Combo', href: '#combo-featured' },
    secondaryCta: { label: 'Thiết kế Combo riêng', href: '#combo-form' },
    trustSignals: ['Giá trọn gói minh bạch', 'Lịch trình chuẩn bị sẵn', 'Đội ngũ hỗ trợ xuyên suốt'],
  },
  combos: [
    {
      id: 'combo-ha-long-trang-mat',
      slug: 'combo-trang-mat-ha-long',
      title: 'Combo Trăng Mật Hạ Long 3N2Đ',
      thumbnail: {
        src: '/images/combo/ha-long-sunset.jpg',
        alt: 'Hoàng hôn buông trên vịnh Hạ Long với những đảo đá vôi in bóng',
        width: 1600,
        height: 1066,
      },
      summary: 'Du thuyền ngủ đêm trên vịnh, ngắm hoàng hôn và đón bình minh cùng người thương.',
      destination: 'Hạ Long',
      category: 'cap-doi',
      priceFrom: 4890000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Du thuyền hạng thương gia', 'Bữa tối lãng mạn trên boong', 'Đưa đón khứ hồi Hà Nội'],
      status: 'published',
      order: 1,
    },
    {
      id: 'combo-sapa-gia-dinh',
      slug: 'combo-sapa-gia-dinh',
      title: 'Combo Gia Đình Khám Phá Sa Pa 3N2Đ',
      thumbnail: {
        src: '/images/combo/sapa-homestay.jpg',
        alt: 'Nhà sàn truyền thống giữa núi rừng Sa Pa',
        width: 1600,
        height: 1066,
      },
      summary: 'Ruộng bậc thang, bản làng và không khí se lạnh — hành trình vừa sức cho cả gia đình.',
      destination: 'Sa Pa',
      category: 'gia-dinh',
      priceFrom: 5290000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Khách sạn trung tâm thị trấn', 'Vé cáp treo Fansipan', 'Hướng dẫn viên địa phương'],
      status: 'published',
      order: 2,
    },
    {
      id: 'combo-ninh-binh-nhom-ban',
      slug: 'combo-ninh-binh-nhom-ban',
      title: 'Combo Nhóm Bạn Trải Nghiệm Ninh Bình 2N1Đ',
      thumbnail: {
        src: '/images/hero/ninh-binh.jpg',
        alt: 'Thuyền chèo tay trên sông giữa núi đá vôi Ninh Bình',
        width: 1920,
        height: 1080,
      },
      summary: 'Chèo thuyền Tràng An, đạp xe qua những cánh đồng lúa — hành trình gắn kết cho nhóm bạn.',
      destination: 'Ninh Bình',
      category: 'nhom-ban',
      priceFrom: 2390000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Vé thuyền Tràng An', 'Xe đạp khám phá làng quê', 'Ăn trưa đặc sản dê núi'],
      status: 'published',
      order: 3,
    },
    {
      id: 'combo-phu-quoc-nghi-duong',
      slug: 'combo-phu-quoc-nghi-duong',
      title: 'Combo Nghỉ Dưỡng Phú Quốc 4N3Đ',
      thumbnail: {
        src: '/images/combo/phu-quoc-sunset.jpg',
        alt: 'Hoàng hôn trên bãi biển Phú Quốc với hàng dừa in bóng',
        width: 1600,
        height: 1066,
      },
      summary: 'Resort ven biển, hồ bơi vô cực và những buổi chiều không vội vã.',
      destination: 'Phú Quốc',
      category: 'nghi-duong',
      priceFrom: 6990000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Vé máy bay khứ hồi', 'Resort 4 sao gần biển', 'Buffet sáng mỗi ngày'],
      status: 'published',
      order: 4,
    },
    {
      id: 'combo-da-nang-gia-dinh',
      slug: 'combo-da-nang-hoi-an-gia-dinh',
      title: 'Combo Gia Đình Đà Nẵng — Hội An 3N2Đ',
      thumbnail: {
        src: '/images/combo/da-nang-dragon-bridge.jpg',
        alt: 'Cầu Rồng Đà Nẵng rực rỡ ánh đèn lúc hoàng hôn',
        width: 1600,
        height: 1068,
      },
      summary: 'Biển Mỹ Khê, phố cổ Hội An và ẩm thực miền Trung cho cả nhà.',
      destination: 'Đà Nẵng',
      category: 'gia-dinh',
      priceFrom: 5590000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Vé máy bay khứ hồi', 'Khách sạn view biển Mỹ Khê', 'Vé tham quan phố cổ Hội An'],
      status: 'published',
      order: 5,
    },
    {
      id: 'combo-nha-trang-nhom-ban',
      slug: 'combo-nha-trang-nhom-ban',
      title: 'Combo Nhóm Bạn Nha Trang 3N2Đ',
      thumbnail: {
        src: '/images/combo/nha-trang-boat.jpg',
        alt: 'Nhóm bạn vui vẻ trên thuyền dạo biển Nha Trang',
        width: 1600,
        height: 1200,
      },
      summary: 'Lặn ngắm san hô, tour đảo và những buổi tối bên bờ biển cùng hội bạn thân.',
      destination: 'Nha Trang',
      category: 'nhom-ban',
      priceFrom: 4590000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Tour 4 đảo trọn ngày', 'Khách sạn trung tâm biển', 'Tặng vé công viên nước'],
      status: 'published',
      order: 6,
    },
    {
      id: 'combo-cat-ba-cap-doi',
      slug: 'combo-cat-ba-lan-ha-bay',
      title: 'Combo Cát Bà — Lan Hạ Bay 2N1Đ',
      thumbnail: {
        src: '/images/combo/cat-ba-kayak.jpg',
        alt: 'Kayak màu cam trên vịnh Lan Hạ yên bình giữa các vách đá vôi',
        width: 1600,
        height: 1066,
      },
      summary: 'Vịnh Lan Hạ yên bình, chèo kayak và một đêm nghỉ dưỡng tách biệt phố thị.',
      destination: 'Cát Bà',
      category: 'cap-doi',
      priceFrom: 3290000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Chèo kayak vịnh Lan Hạ', 'Homestay view biển', 'Đưa đón phà khứ hồi'],
      status: 'published',
      order: 7,
    },
    {
      id: 'combo-team-building-ha-long',
      slug: 'combo-team-building-ha-long',
      title: 'Combo Team Building Doanh Nghiệp — Hạ Long 2N1Đ',
      thumbnail: {
        src: '/images/combo/ha-long-cruise.jpg',
        alt: 'Du thuyền lớn di chuyển giữa các đảo đá vôi trên vịnh Hạ Long',
        width: 1600,
        height: 2400,
      },
      summary: 'Du thuyền riêng, hoạt động gắn kết đội nhóm và gala dinner trên vịnh.',
      destination: 'Hạ Long',
      category: 'doanh-nghiep',
      priceFrom: 3990000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Du thuyền riêng theo đoàn', 'MC & trò chơi team building', 'Gala dinner trên vịnh'],
      status: 'published',
      order: 8,
    },
    {
      id: 'combo-sapa-mua-thu',
      slug: 'combo-sapa-mua-thu',
      title: 'Combo Sa Pa Mùa Lúa Chín (sắp ra mắt)',
      thumbnail: {
        src: '/images/combo/sapa-village.jpg',
        alt: 'Bản làng vùng cao giữa núi rừng Lào Cai',
        width: 1600,
        height: 2400,
      },
      summary: 'Hành trình giới hạn theo mùa lúa chín — đang hoàn thiện lịch trình.',
      destination: 'Sa Pa',
      category: 'nghi-duong',
      priceFrom: 4990000,
      currency: 'VND',
      cta: { label: 'Xem hành trình', href: '#combo-form' },
      highlights: ['Ngắm mùa lúa chín tháng 9', 'Lưu trú homestay bản địa', 'Giới hạn theo mùa'],
      status: 'draft',
      order: 9,
    },
  ],
  categories: [
    {
      id: 'gia-dinh',
      label: 'Gia đình',
      description: 'Lịch trình vừa sức, phòng nghỉ rộng rãi cho cả nhà.',
      image: {
        src: '/images/combo/gia-dinh.jpg',
        alt: 'Một gia đình quây quần tại khu nghỉ dưỡng ven biển',
        width: 1600,
        height: 1066,
      },
      href: '/combo/tat-ca?category=gia-dinh',
      order: 1,
      status: 'published',
    },
    {
      id: 'cap-doi',
      label: 'Cặp đôi',
      description: 'Không gian riêng tư, những khoảnh khắc chỉ có hai người.',
      image: {
        src: '/images/combo/cap-doi.jpg',
        alt: 'Hai người ngắm cảnh sông nước cùng nhau trên cầu',
        width: 1600,
        height: 1066,
      },
      href: '/combo/tat-ca?category=cap-doi',
      order: 2,
      status: 'published',
    },
    {
      id: 'nghi-duong',
      label: 'Nghỉ dưỡng',
      description: 'Chậm lại, tận hưởng từng ngày không cần lên kế hoạch.',
      image: {
        src: '/images/combo/nghi-duong.jpg',
        alt: 'Hồ bơi resort ven biển với ghế nằm dưới hàng dừa',
        width: 1600,
        height: 1066,
      },
      href: '/combo/tat-ca?category=nghi-duong',
      order: 3,
      status: 'published',
    },
    {
      id: 'doanh-nghiep',
      label: 'Doanh nghiệp',
      description: 'Team building, hội nghị và gala dinner trọn gói.',
      image: {
        src: '/images/combo/doanh-nghiep.jpg',
        alt: 'Nhóm nhân sự doanh nghiệp thảo luận trong phòng họp',
        width: 1600,
        height: 1066,
      },
      href: '/combo/tat-ca?category=doanh-nghiep',
      order: 4,
      status: 'published',
    },
    {
      id: 'nhom-ban',
      label: 'Nhóm bạn',
      description: 'Hành trình năng động, chia sẻ chi phí dễ dàng.',
      image: {
        src: '/images/combo/nhom-ban.jpg',
        alt: 'Nhóm bạn ôm nhau ngắm cảnh trên vách núi',
        width: 1600,
        height: 1066,
      },
      href: '/combo/tat-ca?category=nhom-ban',
      order: 5,
      status: 'published',
    },
    {
      id: 'khach-cong-tac',
      label: 'Khách công tác',
      description: 'Sắp xếp nhanh gọn, tối ưu thời gian di chuyển.',
      image: {
        src: '/images/combo/khach-cong-tac.jpg',
        alt: 'Bóng người di chuyển trong nhà ga sân bay dưới ánh nắng',
        width: 1600,
        height: 2400,
      },
      href: '/combo/tat-ca?category=khach-cong-tac',
      order: 6,
      status: 'published',
    },
  ],
  destinationExplorer: {
    eyebrow: 'Điểm đến',
    title: 'Những nơi đáng để bắt đầu',
    description: 'Sáu điểm đến được chọn nhiều nhất trong các hành trình Combo của Minh Việt.',
    destinations: [
      {
        id: 'ha-long',
        slug: 'ha-long',
        name: 'Hạ Long',
        tagline: 'Vịnh di sản, những đêm ngủ trên du thuyền',
        stat: '2 hành trình Combo',
        image: {
          src: '/images/hero/ha-long-bay.jpg',
          alt: 'Vịnh Hạ Long nhìn từ du thuyền lúc hoàng hôn',
          width: 1920,
          height: 1080,
        },
        href: '/combo/tat-ca?destination=H%E1%BA%A1%20Long',
        order: 1,
        status: 'published',
      },
      {
        id: 'sa-pa',
        slug: 'sa-pa',
        name: 'Sa Pa',
        tagline: 'Ruộng bậc thang mùa nào cũng đẹp',
        stat: '1 hành trình Combo',
        image: {
          src: '/images/hero/sapa-terraces.jpg',
          alt: 'Ruộng bậc thang Sa Pa vào mùa lúa chín',
          width: 1920,
          height: 1080,
        },
        href: '/combo/tat-ca?destination=Sa%20Pa',
        order: 2,
        status: 'published',
      },
      {
        id: 'phu-quoc',
        slug: 'phu-quoc',
        name: 'Phú Quốc',
        tagline: 'Đảo ngọc với những khu nghỉ dưỡng ven biển',
        stat: '1 hành trình Combo',
        image: {
          src: '/images/combo/phu-quoc.jpg',
          alt: 'Bãi biển Phú Quốc với hàng dừa và thuyền neo trên biển lặng',
          width: 1600,
          height: 1066,
        },
        href: '/combo/tat-ca?destination=Ph%C3%BA%20Qu%E1%BB%91c',
        order: 3,
        status: 'published',
      },
      {
        id: 'da-nang',
        slug: 'da-nang',
        name: 'Đà Nẵng',
        tagline: 'Thành phố biển hiện đại, gần Hội An cổ kính',
        stat: '1 hành trình Combo',
        image: {
          src: '/images/combo/da-nang.jpg',
          alt: 'Buổi sáng yên bình trên bãi biển Đà Nẵng, phía xa là dãy núi',
          width: 1600,
          height: 1066,
        },
        href: '/combo/tat-ca?destination=%C4%90%C3%A0%20N%E1%BA%B5ng',
        order: 4,
        status: 'published',
      },
      {
        id: 'nha-trang',
        slug: 'nha-trang',
        name: 'Nha Trang',
        tagline: 'Vịnh biển xanh, thiên đường lặn biển',
        stat: '1 hành trình Combo',
        image: {
          src: '/images/combo/nha-trang.jpg',
          alt: 'Bờ biển và đường chân trời thành phố Nha Trang nhìn từ trên cao',
          width: 1600,
          height: 2400,
        },
        href: '/combo/tat-ca?destination=Nha%20Trang',
        order: 5,
        status: 'published',
      },
      {
        id: 'cat-ba',
        slug: 'cat-ba',
        name: 'Cát Bà',
        tagline: 'Đảo hoang sơ cạnh vịnh Lan Hạ',
        stat: '1 hành trình Combo',
        image: {
          src: '/images/combo/cat-ba.jpg',
          alt: 'Bãi biển và vách đá xanh của đảo Cát Bà',
          width: 1600,
          height: 1066,
        },
        href: '/combo/tat-ca?destination=C%C3%A1t%20B%C3%A0',
        order: 6,
        status: 'published',
      },
    ],
  },
  whyCombo: {
    eyebrow: 'Vì sao nên chọn Combo',
    title: 'Một hành trình, không phải nhiều lần đặt chỗ',
    description: 'Combo gộp sẵn những phần việc mất thời gian nhất khi tự sắp xếp một chuyến đi.',
    items: [
      {
        id: 'chuan-bi-tron-ven',
        title: 'Chuẩn bị trọn vẹn, không bỏ sót điều gì',
        description:
          'Từ vé máy bay, khách sạn đến lịch trình từng ngày — mọi chi tiết được sắp xếp sẵn trước khi bạn lên đường.',
        image: {
          src: '/images/combo/trip-planning.jpg',
          alt: 'Lên kế hoạch hành trình cùng bản đồ và la bàn trên bàn',
          width: 1600,
          height: 1066,
        },
      },
      {
        id: 'mot-gia-tron-hanh-trinh',
        title: 'Một mức giá, trọn hành trình',
        description:
          'Giá combo đã gộp sẵn các dịch vụ chính, giúp bạn chủ động ngân sách mà không phát sinh bất ngờ.',
        image: {
          src: '/images/combo/resort-breakfast.jpg',
          alt: 'Bữa sáng bên hồ bơi tại khu nghỉ dưỡng nhiệt đới',
          width: 1600,
          height: 1064,
        },
      },
      {
        id: 'dong-hanh-xuyen-suot',
        title: 'Đồng hành xuyên suốt chuyến đi',
        description:
          'Đội ngũ Minh Việt hỗ trợ từ lúc đặt combo đến khi kết thúc chuyến đi, sẵn sàng xử lý khi có thay đổi.',
        image: {
          src: '/images/combo/hotel-reception.jpg',
          alt: 'Nhân viên lễ tân khách sạn hỗ trợ khách nhận phòng',
          width: 1600,
          height: 1066,
        },
      },
    ],
  },
  articles: [
    {
      id: 'article-chon-khach-san-combo',
      slug: 'chon-khach-san-cho-combo-nghi-duong-gia-dinh',
      title: 'Chọn khách sạn nào cho Combo nghỉ dưỡng gia đình?',
      excerpt: 'Những tiêu chí Minh Việt dùng để chọn khách sạn khi ghép vào một Combo gia đình.',
      image: {
        src: '/images/combo/hotel-room.jpg',
        alt: 'Phòng khách sạn hiện đại với tầm nhìn ra thành phố',
        width: 1600,
        height: 2134,
      },
      publishedAt: '2026-06-02',
      href: '/hotels',
      order: 1,
      isActive: true,
    },
    {
      id: 'article-du-thuyen-ha-long',
      slug: 'du-thuyen-trong-combo-ha-long-nen-chon-hang-phong-nao',
      title: 'Du thuyền trong Combo Hạ Long: nên chọn hạng phòng nào?',
      excerpt: 'So sánh các hạng phòng du thuyền phổ biến trong Combo Hạ Long 2N1Đ và 3N2Đ.',
      image: {
        src: '/images/hero/ha-long-bay.jpg',
        alt: 'Vịnh Hạ Long nhìn từ du thuyền lúc hoàng hôn',
        width: 1920,
        height: 1080,
      },
      publishedAt: '2026-05-20',
      href: '/cruises',
      order: 2,
      isActive: true,
    },
    {
      id: 'article-ve-may-bay-combo',
      slug: 've-may-bay-trong-combo-duoc-tinh-nhu-the-nao',
      title: 'Vé máy bay trong Combo được tính như thế nào?',
      excerpt: 'Giải thích cách Minh Việt ghép vé máy bay khứ hồi vào giá Combo trọn gói.',
      image: {
        src: '/images/combo/airplane-window.jpg',
        alt: 'Hành khách ngồi cạnh cửa sổ máy bay trong chuyến bay',
        width: 1600,
        height: 2400,
      },
      publishedAt: '2026-05-05',
      href: '/ve-may-bay',
      order: 3,
      isActive: true,
    },
    {
      id: 'article-khi-nao-chon-tour-thiet-ke',
      slug: 'khi-nao-nen-chon-tour-thiet-ke-rieng-thay-vi-combo',
      title: 'Khi nào nên chọn Tour thiết kế riêng thay vì Combo có sẵn?',
      excerpt: 'Combo phù hợp khi lịch trình đã rõ ràng — còn khi nào thì nên thiết kế riêng?',
      image: {
        src: '/images/combo/nhom-ban.jpg',
        alt: 'Nhóm bạn ôm nhau ngắm cảnh trên vách núi',
        width: 1600,
        height: 1066,
      },
      publishedAt: '2026-04-18',
      href: '/tour-thiet-ke',
      order: 4,
      isActive: true,
    },
  ],
  finalCta: {
    headline: 'Chưa tìm thấy Combo phù hợp?',
    description: 'Đội ngũ Minh Việt sẽ lắng nghe nhu cầu và thiết kế một Combo riêng cho chuyến đi của bạn.',
    primaryCta: { label: 'Thiết kế Combo riêng', href: '#combo-form' },
  },
}
