import type { HomepageContent } from '@/types/homepage'

/**
 * Local seed content conforming exactly to `HomepageContent`. This is the
 * thing a real CMS integration replaces — every section component reads
 * only from the typed contract in `types/homepage.ts`, never from this
 * file directly, so swapping the fetch implementation in
 * `lib/cms/client.ts` is the only change a future CMS migration needs.
 *
 * Every number shown as proof carries a `source`/`asOf` pair. Nothing
 * here uses fabricated ratings, invented seat counters, or countdown
 * urgency — see the approved Design Audit, section 8 (Trust Signals).
 */
export const homepageContentSeed: HomepageContent = {
  hero: {
    eyebrow: 'Minh Việt Travel · Enterprise Travel & MICE',
    headline: 'Kiến tạo hành trình, nâng tầm trải nghiệm',
    headlineAccent: 'doanh nghiệp',
    subhead:
      'Giải pháp du lịch, sự kiện và công tác trọn gói dành cho doanh nghiệp, tổ chức và khách hàng cao cấp — thẩm định bởi chuyên gia, hỗ trợ bởi AI.',
    primaryCta: { label: 'Nhận tư vấn giải pháp', href: '/contact?intent=corporate' },
    secondaryCta: { label: 'Thử gợi ý AI', href: '#ai-advisor' },
    backgroundImage: {
      src: '/editorial-hero.webp',
      alt: 'Du khách ngắm bình minh trên thung lũng núi đá vôi Việt Nam',
      width: 1920,
      height: 1080,
    },
    proofStat: {
      id: 'years-experience',
      value: 15,
      suffix: '+',
      label: 'Năm kinh nghiệm tổ chức du lịch & MICE',
      source: 'Hồ sơ năng lực Minh Việt Travel',
      asOf: '2026',
    },
  },
  trustStrip: {
    eyebrow: 'Được tin dùng bởi doanh nghiệp & tổ chức trên cả nước',
    segments: [
      { id: 'fdi', label: 'Khu công nghiệp & FDI', icon: 'building' },
      { id: 'gov', label: 'Cơ quan nhà nước', icon: 'landmark' },
      { id: 'association', label: 'Hiệp hội & tổ chức', icon: 'users' },
      { id: 'corporate', label: 'Corporate travel', icon: 'briefcase' },
    ],
    stats: [
      {
        id: 'clients-served',
        value: 5000,
        suffix: '+',
        label: 'Doanh nghiệp đã đồng hành',
        source: 'CRM nội bộ Minh Việt, tổng lũy kế',
        asOf: '2026-Q2',
      },
      {
        id: 'travelers-served',
        value: 200,
        suffix: 'K+',
        label: 'Lượt khách được phục vụ',
        source: 'Báo cáo vận hành nội bộ',
        asOf: '2026-Q2',
      },
      {
        id: 'global-partners',
        value: 60,
        suffix: '+',
        label: 'Đối tác hàng không & lưu trú toàn cầu',
        source: 'Danh mục đối tác Minh Việt',
        asOf: '2026-Q2',
      },
    ],
    partners: [
      { id: 'vietnam-airlines', name: 'Vietnam Airlines', category: 'airline' },
      { id: 'singapore-airlines', name: 'Singapore Airlines', category: 'airline' },
      { id: 'korean-air', name: 'Korean Air', category: 'airline' },
      { id: 'ana', name: 'ANA', category: 'airline' },
      { id: 'marriott', name: 'Marriott', category: 'hotel' },
      { id: 'accor', name: 'Accor', category: 'hotel' },
      { id: 'intercontinental', name: 'InterContinental', category: 'hotel' },
      { id: 'vinpearl', name: 'Vinpearl', category: 'hotel' },
    ],
  },
  coreServices: {
    eyebrow: 'Dịch vụ cốt lõi',
    title: 'Một đầu mối, trọn vẹn hành trình',
    services: [
      { id: 'group-tours', title: 'Tour đoàn', icon: 'group', href: '/tours?type=group' },
      { id: 'mice', title: 'MICE & Sự kiện', icon: 'briefcase', href: '/mice' },
      { id: 'custom-service', title: 'Dịch vụ lẻ', icon: 'sparkles', href: '/services' },
      { id: 'hotels', title: 'Khách sạn', icon: 'building', href: '/hotels' },
      { id: 'cruises', title: 'Du thuyền', icon: 'ship', href: '/cruises' },
      { id: 'flights', title: 'Vé máy bay', icon: 'plane', href: '/flights' },
    ],
  },
  enterpriseMice: {
    badge: 'Giải pháp doanh nghiệp & MICE',
    title: 'Sự kiện đẳng cấp cho doanh nghiệp của bạn',
    description:
      'Hội nghị, team building, gala dinner và incentive — dàn dựng trọn gói, chuyên nghiệp, đạt tiêu chuẩn doanh nghiệp và tổ chức quốc tế.',
    differentiators: [
      {
        id: 'custom-design',
        title: 'Thiết kế riêng',
        description: 'Hành trình linh hoạt theo ngân sách & mục tiêu doanh nghiệp.',
      },
      {
        id: 'full-operation',
        title: 'Vận hành trọn gói',
        description: 'Từ vận chuyển, lưu trú đến sự kiện — một đầu mối duy nhất.',
      },
      {
        id: '24-7-coordination',
        title: 'Điều phối 24/7',
        description: 'Đội ngũ điều hành theo sát trước, trong và sau chuyến đi.',
      },
      {
        id: 'enterprise-standard',
        title: 'Tiêu chuẩn doanh nghiệp',
        description: 'Quy trình, hợp đồng & báo cáo đạt chuẩn đối tác FDI.',
      },
    ],
    proofStat: {
      id: 'mice-programs-delivered',
      value: 300,
      suffix: '+',
      label: 'Chương trình MICE đã triển khai',
      source: 'Báo cáo vận hành nội bộ Minh Việt',
      asOf: '2026-Q2',
    },
    image: {
      src: '/editorial-mice.webp',
      alt: 'Sự kiện gala dinner doanh nghiệp do Minh Việt tổ chức',
      width: 1600,
      height: 1200,
    },
    cta: { label: 'Nhận tư vấn giải pháp MICE', href: '/mice' },
  },
  aiAdvisor: {
    eyebrow: 'Công nghệ & con người',
    title: 'Trợ lý AI, thẩm định bởi',
    titleAccent: 'chuyên gia thật',
    description:
      'Chọn ngân sách, quy mô đoàn và ưu tiên điểm đến — AI của Minh Việt đề xuất hành trình phù hợp kèm mức độ phù hợp và lý do cụ thể. Chuyên viên xác nhận trước khi triển khai.',
    disclosureNote:
      'Đây là gợi ý từ AI dựa trên dữ liệu bạn cung cấp, chưa phải xác nhận cuối cùng — chuyên viên Minh Việt sẽ liên hệ để xác nhận tính khả thi trước khi triển khai.',
    questions: [
      {
        id: 'budget',
        label: 'Ngân sách dự kiến',
        placeholder: 'Chọn mức ngân sách',
        options: [
          { value: 'under-15tr', label: 'Dưới 15 triệu / người' },
          { value: '15-30tr', label: '15 - 30 triệu / người' },
          { value: '30-70tr', label: '30 - 70 triệu / người' },
          { value: '70tr-plus', label: 'Trên 70 triệu / người' },
        ],
      },
      {
        id: 'groupSize',
        label: 'Quy mô đoàn',
        placeholder: 'Chọn quy mô',
        options: [
          { value: 'individual', label: 'Cá nhân / cặp đôi' },
          { value: 'small-group', label: 'Nhóm nhỏ (dưới 10 người)' },
          { value: 'large-group', label: 'Đoàn lớn (10 - 50 người)' },
          { value: 'corporate', label: 'Doanh nghiệp / tổ chức (50+ người)' },
        ],
      },
      {
        id: 'preference',
        label: 'Ưu tiên điểm đến',
        placeholder: 'Chọn ưu tiên',
        options: [
          { value: 'beach', label: 'Biển & nghỉ dưỡng' },
          { value: 'mountain', label: 'Núi & thiên nhiên' },
          { value: 'culture', label: 'Văn hoá & di sản' },
          { value: 'city', label: 'Đô thị & hiện đại' },
        ],
      },
    ],
    humanHandoffCta: { label: 'Nói chuyện với chuyên viên', href: '/contact?intent=ai-advisor' },
  },
  featuredJourneys: {
    eyebrow: 'Hành trình tuyển chọn',
    title: 'Những chuyến đi',
    titleAccent: 'đáng nhớ',
    filters: [
      { id: 'all', label: 'Tất cả' },
      { id: 'asia', label: 'Châu Á' },
      { id: 'europe', label: 'Châu Âu' },
      { id: 'domestic', label: 'Nội địa' },
    ],
    journeys: [
      {
        id: 'tokyo',
        title: 'Tokyo — Núi Phú Sĩ — Hakone',
        country: 'Nhật Bản',
        category: 'asia',
        duration: '5N4Đ',
        departure: 'Hà Nội',
        nextDeparture: '25/07/2026',
        priceFrom: 27900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-tokyo.webp', alt: 'Tokyo và núi Phú Sĩ', width: 800, height: 600 },
        href: '/tour/tokyo',
        matchTags: ['budget:15-30tr', 'group:individual', 'group:small-group', 'preference:culture', 'preference:mountain'],
      },
      {
        id: 'korea',
        title: 'Seoul — Nami — Everland mùa thu',
        country: 'Hàn Quốc',
        category: 'asia',
        duration: '5N4Đ',
        departure: 'Hà Nội',
        nextDeparture: '28/07/2026',
        priceFrom: 16900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'limited',
        image: { src: '/tour-korea.webp', alt: 'Seoul và đảo Nami', width: 800, height: 600 },
        href: '/tour/korea',
        matchTags: ['budget:under-15tr', 'budget:15-30tr', 'group:individual', 'group:small-group', 'preference:city', 'preference:mountain'],
      },
      {
        id: 'europe',
        title: 'Thụy Sĩ — Pháp — Ý cao cấp',
        country: 'Châu Âu',
        category: 'europe',
        duration: '9N8Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '02/08/2026',
        priceFrom: 64900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-europe.webp', alt: 'Thụy Sĩ, Pháp, Ý', width: 800, height: 600 },
        href: '/tour/europe',
        matchTags: ['budget:30-70tr', 'budget:70tr-plus', 'group:small-group', 'group:corporate', 'preference:culture', 'preference:city'],
      },
      {
        id: 'bali',
        title: 'Bali — Thiên đường nghỉ dưỡng',
        country: 'Indonesia',
        category: 'asia',
        duration: '4N3Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '30/07/2026',
        priceFrom: 13900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-bali.webp', alt: 'Bali nghỉ dưỡng', width: 800, height: 600 },
        href: '/tour/bali',
        matchTags: ['budget:under-15tr', 'group:individual', 'group:small-group', 'preference:beach'],
      },
      {
        id: 'phuquoc',
        title: 'Phú Quốc — Nam Đảo — Hòn Thơm',
        country: 'Việt Nam',
        category: 'domestic',
        duration: '3N2Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '21/07/2026',
        priceFrom: 4990000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'almost-full',
        image: { src: '/dest-vietnam.webp', alt: 'Phú Quốc, Việt Nam', width: 800, height: 600 },
        href: '/tour/phuquoc',
        matchTags: ['budget:under-15tr', 'group:individual', 'group:small-group', 'group:large-group', 'preference:beach'],
      },
      {
        id: 'singapore',
        title: 'Singapore — Sentosa — Gardens by the Bay',
        country: 'Singapore',
        category: 'asia',
        duration: '4N3Đ',
        departure: 'Hà Nội',
        nextDeparture: '26/07/2026',
        priceFrom: 12900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/dest-singapore.webp', alt: 'Singapore, Sentosa', width: 800, height: 600 },
        href: '/tour/singapore',
        matchTags: ['budget:under-15tr', 'budget:15-30tr', 'group:small-group', 'group:corporate', 'preference:city'],
      },
    ],
    viewAllCta: { label: 'Xem tất cả tour', href: '/tours' },
  },
  destinations: {
    eyebrow: 'Điểm đến',
    title: 'Thế giới trong',
    titleAccent: 'tầm với',
    destinations: [
      { id: 'japan', name: 'Nhật Bản', tagline: 'Tinh tế & bốn mùa', journeyCount: 24, image: { src: '/dest-japan.webp', alt: 'Nhật Bản', width: 600, height: 800 }, href: '/destinations/japan' },
      { id: 'korea', name: 'Hàn Quốc', tagline: 'Năng động & hiện đại', journeyCount: 20, image: { src: '/tour-korea.webp', alt: 'Hàn Quốc', width: 600, height: 800 }, href: '/destinations/korea' },
      { id: 'europe', name: 'Châu Âu', tagline: 'Cổ kính & tráng lệ', journeyCount: 16, image: { src: '/tour-europe.webp', alt: 'Châu Âu', width: 600, height: 800 }, href: '/destinations/europe' },
      { id: 'usa', name: 'Mỹ', tagline: 'Rộng lớn & tự do', journeyCount: 12, image: { src: '/dest-usa.webp', alt: 'Mỹ', width: 600, height: 800 }, href: '/destinations/usa' },
      { id: 'singapore', name: 'Singapore', tagline: 'Hiện đại & sôi động', journeyCount: 18, image: { src: '/dest-singapore.webp', alt: 'Singapore', width: 600, height: 800 }, href: '/destinations/singapore' },
      { id: 'vietnam', name: 'Việt Nam', tagline: 'Di sản & thiên nhiên', journeyCount: 52, image: { src: '/dest-vietnam.webp', alt: 'Việt Nam', width: 600, height: 800 }, href: '/destinations/vietnam' },
    ],
  },
  brandCenter: {
    eyebrow: 'Dấu ấn Minh Việt',
    title: 'Năng lực & uy tín được khẳng định',
    description:
      'Trung tâm thương hiệu ghi nhận năng lực tổ chức, đội ngũ lãnh đạo và mạng lưới đối tác của Minh Việt — không phải một trang blog.',
    stories: [
      {
        id: 'fdi-alliance',
        category: 'Dấu ấn Minh Việt',
        title: 'Minh Việt ký kết chiến lược cùng liên minh khu công nghiệp phía Bắc',
        description: 'Đồng hành tổ chức chương trình du lịch và MICE cho hàng chục nghìn lao động và chuyên gia FDI.',
        date: '18.06.2026',
        image: { src: '/brand-signing.webp', alt: 'Lễ ký kết chiến lược', width: 1200, height: 900 },
        href: '/brand/news/fdi-alliance',
        size: 'large',
      },
      {
        id: 'leadership-message',
        category: 'Lãnh đạo & chuyên gia',
        title: 'Thông điệp từ Ban điều hành về hành trình chuyển đổi số',
        description: 'Tầm nhìn AI-first cho ngành du lịch doanh nghiệp.',
        date: '02.06.2026',
        image: { src: '/brand-leadership.webp', alt: 'Ban lãnh đạo Minh Việt', width: 800, height: 800 },
        href: '/brand/leadership',
        size: 'small',
      },
      {
        id: 'japan-1200-guests',
        category: 'Năng lực tổ chức',
        title: 'Tổ chức hành trình quy mô lớn tại Nhật Bản',
        description: 'Vận hành hậu cần quy mô lớn với tiêu chuẩn cao cấp.',
        date: '20.05.2026',
        image: { src: '/brand-group.webp', alt: 'Đoàn khách tại Nhật Bản', width: 800, height: 800 },
        href: '/brand/news/japan-group',
        size: 'small',
      },
    ],
    cta: { label: 'Xem hồ sơ năng lực', href: '/about' },
  },
  finalCta: {
    corporate: {
      label: 'Doanh nghiệp / Tổ chức',
      title: 'Nâng tầm hành trình doanh nghiệp của bạn',
      description:
        'Đội ngũ chuyên gia sẵn sàng thiết kế giải pháp du lịch, sự kiện và MICE phù hợp với quy mô và mục tiêu tổ chức của bạn.',
      cta: { label: 'Nhận tư vấn giải pháp', href: '#lead-form' },
    },
    individual: {
      label: 'Khách cá nhân',
      title: 'Sẵn sàng cho chuyến đi tiếp theo',
      description: 'Gửi yêu cầu và chuyên viên tư vấn sẽ liên hệ để xác nhận hành trình phù hợp với bạn.',
      cta: { label: 'Gửi yêu cầu đặt chỗ', href: '#lead-form' },
    },
    phone: '0934 368 132',
    zaloHref: 'https://zalo.me/0934368132',
  },
  seo: {
    title: 'Minh Việt Travel — Kiến tạo hành trình, kết nối giá trị',
    description:
      'Đối tác tin cậy của doanh nghiệp, tổ chức & khách hàng cao cấp. Tour đoàn, MICE & Sự kiện, Khách sạn, Du thuyền, Vé máy bay, Visa — trải nghiệm chuyên nghiệp, ứng dụng AI.',
    canonicalPath: '/',
    organizationName: 'Công ty Cổ phần Thương mại & Dịch vụ Du lịch Minh Việt',
    organizationLogo: '/logo-minhviet.png',
    contactPhone: '+84934368132',
    contactEmail: 'info@minhviettravel.com',
    addressLocality: 'Hải Phòng',
    addressCountry: 'VN',
  },
}
