import type { HomepageContent } from '@/types/homepage'

/**
 * Local seed content conforming exactly to `HomepageContent`. This is the
 * thing a real CMS integration replaces — every section component reads
 * only from the typed contract in `types/homepage.ts`, never from this
 * file directly, so swapping the fetch implementation in
 * `lib/cms/client.ts` is the only change a future CMS migration needs.
 *
 * Every number shown as proof carries a `source`/`asOf` pair. Nothing
 * here uses fabricated ratings, invented seat counters, or countdown
 * urgency — see the approved Design Audit, section 8 (Trust Signals).
 */
export const homepageContentSeed: HomepageContent = {
  hero: {
    eyebrow: 'Minh Việt Travel · Enterprise Travel & MICE',
    headline: 'Kiến tạo hành trình, nâng tầm trải nghiệm',
    headlineAccent: 'doanh nghiệp',
    subhead:
      'Giải pháp du lịch, sự kiện và công tác trọn gói dành cho doanh nghiệp, tổ chức và khách hàng cao cấp — thẩm định bởi chuyên gia, hỗ trợ bởi AI.',
    primaryCta: { label: 'Thiết kế chương trình riêng', href: '/contact?intent=corporate' },
    secondaryCta: { label: 'Khám phá tour có sẵn', href: '#tour-ghep-quoc-te' },
    backgroundImage: {
      src: '/editorial-hero.webp',
      alt: 'Du khách ngắm bình minh trên thung lũng núi đá vôi Việt Nam',
      width: 1920,
      height: 1080,
    },
    proofStat: {
      id: 'years-experience',
      value: 15,
      suffix: '+',
      label: 'Năm kinh nghiệm tổ chức du lịch & MICE',
      source: 'Hồ sơ năng lực Minh Việt Travel',
      asOf: '2026',
    },
  },
  trustStrip: {
    eyebrow: 'Được tin dùng bởi doanh nghiệp & tổ chức trên cả nước',
    positioning: {
      headline: 'Minh Việt không chỉ bán tour — Minh Việt thiết kế và tổ chức toàn bộ hành trình.',
      description:
        'Đội ngũ chuyên trách thiết kế chương trình riêng cho tour doanh nghiệp, MICE, hội nghị và tour gia đình — song song phân phối tour ghép quốc tế, vé máy bay, du thuyền, khách sạn, vé vui chơi, visa và bảo hiểm cho khách cần dịch vụ có sẵn.',
    },
    segments: [
      { id: 'fdi', label: 'Khu công nghiệp & FDI', icon: 'building' },
      { id: 'gov', label: 'Cơ quan nhà nước', icon: 'landmark' },
      { id: 'association', label: 'Hiệp hội & tổ chức', icon: 'users' },
      { id: 'corporate', label: 'Corporate travel', icon: 'briefcase' },
    ],
    stats: [
      {
        id: 'clients-served',
        value: 5000,
        suffix: '+',
        label: 'Doanh nghiệp đã đồng hành',
        source: 'CRM nội bộ Minh Việt, tổng lũy kế',
        asOf: '2026-Q2',
      },
      {
        id: 'travelers-served',
        value: 200,
        suffix: 'K+',
        label: 'Lượt khách được phục vụ',
        source: 'Báo cáo vận hành nội bộ',
        asOf: '2026-Q2',
      },
      {
        id: 'global-partners',
        value: 60,
        suffix: '+',
        label: 'Đối tác hàng không & lưu trú toàn cầu',
        source: 'Danh mục đối tác Minh Việt',
        asOf: '2026-Q2',
      },
    ],
    partners: [
      { id: 'vietnam-airlines', name: 'Vietnam Airlines', category: 'airline' },
      { id: 'singapore-airlines', name: 'Singapore Airlines', category: 'airline' },
      { id: 'korean-air', name: 'Korean Air', category: 'airline' },
      { id: 'ana', name: 'ANA', category: 'airline' },
      { id: 'marriott', name: 'Marriott', category: 'hotel' },
      { id: 'accor', name: 'Accor', category: 'hotel' },
      { id: 'intercontinental', name: 'InterContinental', category: 'hotel' },
      { id: 'vinpearl', name: 'Vinpearl', category: 'hotel' },
    ],
  },
  coreServices: {
    eyebrow: 'Dịch vụ cốt lõi',
    title: 'Một đầu mối, trọn vẹn hành trình',
    groups: [
      {
        id: 'bespoke',
        label: 'Thiết kế theo yêu cầu',
        services: [
          { id: 'group-tours', title: 'Tour đoàn', icon: 'group', href: '/tours?type=group' },
          { id: 'mice', title: 'MICE & Sự kiện', icon: 'briefcase', href: '/mice' },
        ],
      },
      {
        id: 'ready-made',
        label: 'Có sẵn — khám phá ngay',
        services: [
          { id: 'custom-service', title: 'Dịch vụ lẻ', icon: 'sparkles', href: '/services' },
          { id: 'hotels', title: 'Khách sạn', icon: 'building', href: '/hotels' },
          { id: 'cruises', title: 'Du thuyền', icon: 'ship', href: '/cruises' },
          { id: 'flights', title: 'Vé máy bay', icon: 'plane', href: '/flights' },
          { id: 'tickets', title: 'Vé vui chơi', icon: 'ticket', href: '/tickets' },
        ],
      },
    ],
  },
  enterpriseMice: {
    badge: 'Giải pháp doanh nghiệp & MICE',
    title: 'Sự kiện đẳng cấp cho doanh nghiệp của bạn',
    description:
      'Hội nghị, team building, gala dinner và incentive — dàn dựng trọn gói, chuyên nghiệp, đạt tiêu chuẩn doanh nghiệp và tổ chức quốc tế.',
    story:
      'Từ tiếp nhận yêu cầu đến nghiệm thu sau sự kiện, một đội điều phối duy nhất đồng hành cùng doanh nghiệp qua từng bước — không bàn giao giữa chừng, không phát sinh đầu mối thứ hai.',
    process: [
      'Tiếp nhận yêu cầu',
      'Lên Concept',
      'Thiết kế chương trình',
      'Điều phối',
      'Vận hành',
      'Nghiệm thu',
    ],
    proofStat: {
      id: 'mice-programs-delivered',
      value: 300,
      suffix: '+',
      label: 'Chương trình MICE đã triển khai',
      source: 'Báo cáo vận hành nội bộ Minh Việt',
      asOf: '2026-Q2',
    },
    image: {
      src: '/editorial-mice.webp',
      alt: 'Sự kiện gala dinner doanh nghiệp do Minh Việt tổ chức',
      width: 1600,
      height: 1200,
    },
    cta: { label: 'Yêu cầu thiết kế chương trình', href: '/contact?intent=corporate' },
  },
  aiAdvisor: {
    eyebrow: 'Công nghệ & con người',
    title: 'Trợ lý AI, thẩm định bởi',
    titleAccent: 'chuyên gia thật',
    description:
      'Chọn ngân sách, quy mô đoàn và ưu tiên điểm đến — AI của Minh Việt đề xuất hành trình phù hợp kèm mức độ phù hợp và lý do cụ thể. Chuyên viên xác nhận trước khi triển khai.',
    disclosureNote:
      'Đây là gợi ý từ AI dựa trên dữ liệu bạn cung cấp, chưa phải xác nhận cuối cùng — chuyên viên Minh Việt sẽ liên hệ để xác nhận tính khả thi trước khi triển khai.',
    questions: [
      {
        id: 'budget',
        label: 'Ngân sách dự kiến',
        placeholder: 'Chọn mức ngân sách',
        options: [
          { value: 'under-15tr', label: 'Dưới 15 triệu / người' },
          { value: '15-30tr', label: '15 - 30 triệu / người' },
          { value: '30-70tr', label: '30 - 70 triệu / người' },
          { value: '70tr-plus', label: 'Trên 70 triệu / người' },
        ],
      },
      {
        id: 'groupSize',
        label: 'Quy mô đoàn',
        placeholder: 'Chọn quy mô',
        options: [
          { value: 'individual', label: 'Cá nhân / cặp đôi' },
          { value: 'small-group', label: 'Nhóm nhỏ (dưới 10 người)' },
          { value: 'large-group', label: 'Đoàn lớn (10 - 50 người)' },
          { value: 'corporate', label: 'Doanh nghiệp / tổ chức (50+ người)' },
        ],
      },
      {
        id: 'preference',
        label: 'Ưu tiên điểm đến',
        placeholder: 'Chọn ưu tiên',
        options: [
          { value: 'beach', label: 'Biển & nghỉ dưỡng' },
          { value: 'mountain', label: 'Núi & thiên nhiên' },
          { value: 'culture', label: 'Văn hoá & di sản' },
          { value: 'city', label: 'Đô thị & hiện đại' },
        ],
      },
    ],
    humanHandoffCta: { label: 'Nói chuyện với chuyên viên', href: '/contact?intent=ai-advisor' },
  },
  featuredJourneys: {
    eyebrow: 'Tour ghép quốc tế',
    title: 'Khởi hành định kỳ,',
    titleAccent: 'ghép đoàn theo lịch có sẵn',
    filters: [
      { id: 'all', label: 'Tất cả' },
      { id: 'asia', label: 'Châu Á' },
      { id: 'europe', label: 'Châu Âu' },
      { id: 'domestic', label: 'Nội địa' },
    ],
    journeys: [
      {
        id: 'tokyo',
        title: 'Tokyo — Núi Phú Sĩ — Hakone',
        country: 'Nhật Bản',
        category: 'asia',
        duration: '5N4Đ',
        departure: 'Hà Nội',
        nextDeparture: '25/07/2026',
        priceFrom: 27900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-tokyo.webp', alt: 'Tokyo và núi Phú Sĩ', width: 800, height: 600 },
        href: '/tour/tokyo',
        matchTags: ['budget:15-30tr', 'group:individual', 'group:small-group', 'preference:culture', 'preference:mountain'],
      },
      {
        id: 'korea',
        title: 'Seoul — Nami — Everland mùa thu',
        country: 'Hàn Quốc',
        category: 'asia',
        duration: '5N4Đ',
        departure: 'Hà Nội',
        nextDeparture: '28/07/2026',
        priceFrom: 16900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'limited',
        image: { src: '/tour-korea.webp', alt: 'Seoul và đảo Nami', width: 800, height: 600 },
        href: '/tour/korea',
        matchTags: ['budget:under-15tr', 'budget:15-30tr', 'group:individual', 'group:small-group', 'preference:city', 'preference:mountain'],
      },
      {
        id: 'europe',
        title: 'Thụy Sĩ — Pháp — Ý cao cấp',
        country: 'Châu Âu',
        category: 'europe',
        duration: '9N8Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '02/08/2026',
        priceFrom: 64900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-europe.webp', alt: 'Thụy Sĩ, Pháp, Ý', width: 800, height: 600 },
        href: '/tour/europe',
        matchTags: ['budget:30-70tr', 'budget:70tr-plus', 'group:small-group', 'group:corporate', 'preference:culture', 'preference:city'],
      },
      {
        id: 'bali',
        title: 'Bali — Thiên đường nghỉ dưỡng',
        country: 'Indonesia',
        category: 'asia',
        duration: '4N3Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '30/07/2026',
        priceFrom: 13900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/tour-bali.webp', alt: 'Bali nghỉ dưỡng', width: 800, height: 600 },
        href: '/tour/bali',
        matchTags: ['budget:under-15tr', 'group:individual', 'group:small-group', 'preference:beach'],
      },
      {
        id: 'phuquoc',
        title: 'Phú Quốc — Nam Đảo — Hòn Thơm',
        country: 'Việt Nam',
        category: 'domestic',
        duration: '3N2Đ',
        departure: 'TP. Hồ Chí Minh',
        nextDeparture: '21/07/2026',
        priceFrom: 4990000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'almost-full',
        image: { src: '/dest-vietnam.webp', alt: 'Phú Quốc, Việt Nam', width: 800, height: 600 },
        href: '/tour/phuquoc',
        matchTags: ['budget:under-15tr', 'group:individual', 'group:small-group', 'group:large-group', 'preference:beach'],
      },
      {
        id: 'singapore',
        title: 'Singapore — Sentosa — Gardens by the Bay',
        country: 'Singapore',
        category: 'asia',
        duration: '4N3Đ',
        departure: 'Hà Nội',
        nextDeparture: '26/07/2026',
        priceFrom: 12900000,
        priceType: 'estimate',
        currency: 'VND',
        availability: 'open',
        image: { src: '/dest-singapore.webp', alt: 'Singapore, Sentosa', width: 800, height: 600 },
        href: '/tour/singapore',
        matchTags: ['budget:under-15tr', 'budget:15-30tr', 'group:small-group', 'group:corporate', 'preference:city'],
      },
    ],
    viewAllCta: { label: 'Khám phá tour', href: '/tours' },
  },
  destinations: {
    eyebrow: 'Điểm đến',
    title: 'Thế giới trong',
    titleAccent: 'tầm với',
    destinations: [
      { id: 'japan', name: 'Nhật Bản', tagline: 'Tinh tế & bốn mùa', journeyCount: 24, image: { src: '/dest-japan.webp', alt: 'Nhật Bản', width: 600, height: 800 }, href: '/destinations/japan' },
      { id: 'korea', name: 'Hàn Quốc', tagline: 'Năng động & hiện đại', journeyCount: 20, image: { src: '/tour-korea.webp', alt: 'Hàn Quốc', width: 600, height: 800 }, href: '/destinations/korea' },
      { id: 'europe', name: 'Châu Âu', tagline: 'Cổ kính & tráng lệ', journeyCount: 16, image: { src: '/tour-europe.webp', alt: 'Châu Âu', width: 600, height: 800 }, href: '/destinations/europe' },
      { id: 'usa', name: 'Mỹ', tagline: 'Rộng lớn & tự do', journeyCount: 12, image: { src: '/dest-usa.webp', alt: 'Mỹ', width: 600, height: 800 }, href: '/destinations/usa' },
      { id: 'singapore', name: 'Singapore', tagline: 'Hiện đại & sôi động', journeyCount: 18, image: { src: '/dest-singapore.webp', alt: 'Singapore', width: 600, height: 800 }, href: '/destinations/singapore' },
      { id: 'vietnam', name: 'Việt Nam', tagline: 'Di sản & thiên nhiên', journeyCount: 52, image: { src: '/dest-vietnam.webp', alt: 'Việt Nam', width: 600, height: 800 }, href: '/destinations/vietnam' },
    ],
  },
  brandCenter: {
    eyebrow: 'Năng lực',
    title: 'Năng lực & uy tín được khẳng định',
    description:
      'Trung tâm thương hiệu ghi nhận năng lực tổ chức, đội ngũ lãnh đạo và mạng lưới đối tác của Minh Việt — không phải một trang blog.',
    stories: [
      {
        id: 'fdi-alliance',
        category: 'Dấu ấn Minh Việt',
        title: 'Minh Việt ký kết chiến lược cùng liên minh khu công nghiệp phía Bắc',
        description: 'Đồng hành tổ chức chương trình du lịch và MICE cho hàng chục nghìn lao động và chuyên gia FDI.',
        date: '18.06.2026',
        image: { src: '/brand-signing.webp', alt: 'Lễ ký kết chiến lược', width: 1200, height: 900 },
        href: '/brand/news/fdi-alliance',
        size: 'large',
      },
      {
        id: 'leadership-message',
        category: 'Lãnh đạo & chuyên gia',
        title: 'Thông điệp từ Ban điều hành về hành trình chuyển đổi số',
        description: 'Tầm nhìn AI-first cho ngành du lịch doanh nghiệp.',
        date: '02.06.2026',
        image: { src: '/brand-leadership.webp', alt: 'Ban lãnh đạo Minh Việt', width: 800, height: 800 },
        href: '/brand/leadership',
        size: 'small',
      },
      {
        id: 'japan-1200-guests',
        category: 'Năng lực tổ chức',
        title: 'Tổ chức hành trình quy mô lớn tại Nhật Bản',
        description: 'Vận hành hậu cần quy mô lớn với tiêu chuẩn cao cấp.',
        date: '20.05.2026',
        image: { src: '/brand-group.webp', alt: 'Đoàn khách tại Nhật Bản', width: 800, height: 800 },
        href: '/brand/news/japan-group',
        size: 'small',
      },
    ],
    cta: { label: 'Xem hồ sơ năng lực', href: '/about' },
  },
  finalCta: {
    corporate: {
      eyebrow: 'DOANH NGHIỆP / TỔ CHỨC',
      label: 'Doanh nghiệp / Tổ chức',
      title: 'Nâng tầm hành trình doanh nghiệp của bạn',
      description:
        'Đội ngũ chuyên gia Minh Việt sẵn sàng thiết kế giải pháp du lịch, sự kiện và MICE phù hợp với quy mô, ngân sách và mục tiêu của tổ chức.',
      cta: { label: 'Gửi yêu cầu tư vấn', href: '#lead-form' },
    },
    individual: {
      eyebrow: 'KHÁCH HÀNG CÁ NHÂN',
      label: 'Khách hàng cá nhân',
      title: 'Sẵn sàng cho chuyến đi tiếp theo',
      description:
        'Chia sẻ nhu cầu của bạn, chuyên viên Minh Việt sẽ tư vấn hành trình phù hợp với thời gian, ngân sách và sở thích.',
      cta: { label: 'Gửi yêu cầu tư vấn', href: '#lead-form' },
    },
    phone: '0934 368 132',
    zaloHref: 'https://zalo.me/0934368132',
  },
  seo: {
    title: 'Minh Việt Travel — Kiến tạo hành trình, kết nối giá trị',
    description:
      'Đối tác tin cậy của doanh nghiệp, tổ chức & khách hàng cao cấp. Tour đoàn, MICE & Sự kiện, Khách sạn, Du thuyền, Vé máy bay, Visa — trải nghiệm chuyên nghiệp, ứng dụng AI.',
    canonicalPath: '/',
    organizationName: 'Công ty Cổ phần Thương mại & Dịch vụ Du lịch Minh Việt',
    organizationLogo: '/logo-minhviet.png',
    contactPhone: '+84934368132',
    contactEmail: 'info@minhviettravel.com',
    addressLocality: 'Hải Phòng',
    addressCountry: 'VN',
  },
}
